name: CI / CD

on: [pull_request, workflow_dispatch]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install -r requirements.test.txt

      - name: Run tests
        run: pytest tests/unit --no-cov

      - name: Install build
        run: pip install build

      - name: Build package
        run: python -m build
